services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=file:./dev.db
    volumes:
      - ./backend/prisma:/app/prisma
      - ./backend/dev.db:/app/dev.db
    networks:
      - crypto-app

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - crypto-app

networks:
  crypto-app:
    driver: bridge 